### PR TITLE
Added Test.msg to src directory

### LINKED ISSUE #2: Host contents of tarball in this repository (instead of the tarball itself)
This is used in the benchmark programs, so needs to be released.

### PR DESCRIPTION
**Pull request by henrik7264**

### CODE REVIEW

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
I realise we don't have any packages here, but could you least put it in a directory named `ros2_msg `?

We'll convert that into a ROS 2 package later -- and change the name (as it's too generic right now).

**Comment by henrik7264** [comment]
All the information should be available in the rxros2_performance_test.tgz file.

**Comment by gavanderhoorn** [comment]
I don't understand what you mean by that.

---

Edit: oh, you mean the tarbal already contains a set of ROS pkgs, including the `ros2_msg` package.

Then this becomes an entirely different issue.

I'll close this and change the subject of #2.

**Comment by henrik7264** [comment]
Yes.

**Pull request closed without merging**
